# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BopTop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BopTop

pod "LKAlertController"

  target 'BopTopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BopTopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
